[tool.black]
line-length = 127
target-version = ['py311', 'py312']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | __pycache__
  | migrations
  | static
  | media
)/
'''

[tool.isort]
profile = "black"
line_length = 127
skip_gitignore = true
skip = [".venv", "venv", "migrations"]
known_first_party = ["api", "core"]
known_django = ["django"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
